<?php

/**
 * Implements hook_islandora_required_objects().
 */
function ucla_pdf_islandora_required_objects() {
  // module path
  $module_path = drupal_get_path('module', 'ucla_pdf');

  return array(
    'ucla_pdf' => array(
      'title' => 'UCLA PDF',
      'objects' => array(
        array(
          'pid' => 'ucla:TahrirPdfCModel',
          'label' => 'UCLA PDF content model',
          'cmodel' => 'fedora-system:ContentModel-3.0',
          'datastreams' => array(
            array(
              'dsid' => 'DS-COMPOSITE-MODEL',
              'label' => 'DS-COMPOSITE-MODEL',
              'mimetype' => 'text/xml',
              'control_group' => 'X',
              'datastream_file' => "$module_path/xml/ucla_pdf_ds_composite_model.xml",
            ),
          ),
        ),
        array(
          'pid' => 'ucla:tahrir_pdf_collection',
          'label' => 'Tahrir PDF collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'label' => 'Collection policy',
              'mimetype' => 'text/xml',
              'control_group' => 'X',
              'datastream_file' => "$module_path/xml/ucla_pdf_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'label' => 'Thumbnail',
              'mimetype' => 'image/png',
              'control_group' => 'M',
              'datastream_file' => "$module_path/images/folder.png",
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function ucla_pdf_islandora_content_model_forms_form_associations() {
  return array(
    'ucla_pdf_mods_form' => array(
      'content_model' => 'ucla:TahrirPdfCModel',
      'form_name' => 'PDF MODS form',
      'dsid' => 'MODS',
      'title_field' => "['titleInfo']['title']",
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_ingest_pre_ingest().
 *
 * Add in islandora:sp_pdf, so it gets handled in largely the same way.
 */
function ucla_pdf_ucla_TahrirPdfCModel_islandora_ingest_pre_ingest($obj, $cm, $col) {
  $obj->relationships->add(FEDORA_MODEL_URI, 'hasModel', 'islandora:sp_pdf');
}


/**
 * Implements hook_menu().
 */
function ucla_pdf_menu() {
  return array(
    'islandora/object/%islandora_object/view_translation' => array(
      'title' => 'Translation (English)',
      'page callback' => 'ucla_pdf_view_translation',
      'page arguments' => array(2, 'TRANSLATION-EN'),
      'access callback' => 'ucla_pdf_access',
      'access arguments' => array(2, 'TRANSLATION-EN'),
      'type' => MENU_LOCAL_TASK,
    ),
    'islandora/object/%islandora_object/view_transcription' => array(
      'title' => 'Transcription',
      'page callback' => 'ucla_pdf_view_transcription',
      'page arguments' => array(2, 'TRANSCRIPTION'),
      'access callback' => 'ucla_pdf_access',
      'access arguments' => array(2, 'TRANSCRIPTION'),
      'type' => MENU_LOCAL_TASK,
    ),
    'islandora/object/%islandora_object/download_translation' => array(
      'title' => 'Download text',
      'page callback' => 'ucla_pdf_download_translation',
      'page arguments' => array(2, 'TRANSLATION-EN'),
      'access callback' => 'ucla_pdf_access',
      'access arguments' => array(2, 'TRANSLATION-EN'),
      'type' => MENU_CALLBACK,
    ),
    //'islandora/object/%islandora_object/view_dc' => array(
    //  'title' => 'DC (For testing)',
    //  'page callback' => 'ucla_pdf_view_text',
    //  'page arguments' => array(2, 'DC'),
    //  'access callback' => 'ucla_pdf_access',
    //  'access arguments' => array(2, 'DC'),
    //  'type' => MENU_LOCAL_TASK,
    //),
  );
}

/**
 * Check that our streams exist, before showing the paths. 
 *
 *  @param $object - FedoraObject - Tuque object containing the datastream
 *  @param $dsid - string - The id of the datastream in the Tuque object
 */
function ucla_pdf_access($object = NULL, $dsid = NULL) {
  return in_array('ucla:TahrirPdfCModel', $object->models) && isset($object[$dsid]) && islandora_access_callback($object, FEDORA_VIEW);
}

/**
 *  Formats text from a datastream for html viewing.
 *
 *  @param $object - FedoraObject - Tuque object containing the datastream
 *  @param $dsid - string - The id of the datastream in the Tuque object that contains
 *    the text
 */
function _ucla_pdf_format_datastream_text($object, $dsid) {
  return check_plain($object[$dsid]->content);
}

/**
 *  Serves the supplied text as a file for the user to download.
 *
 *  @param $text - string - The text to serve
 *  @param $filename - string - The filename to download as (excludes
 *    extension)
 */
function _ucla_pdf_serve_text_as_file($text, $filename) {
  header("Content-type: application/octet-stream");
  header("Content-Disposition: attachment; filename=\"{$filename}.txt\"");
  echo $text;
}

/**
 *  Page callback to download a string of text contained in a datastream.
 *
 *  @param $object - FedoraObject - Tuque object containing the datastream
 *  @param $dsid - string - The id of the datastream in the Tuque object that contains
 *    the text
 */
function ucla_pdf_download_translation($object, $dsid) {
  _ucla_pdf_serve_text_as_file($object[$dsid]->content, $dsid);
  return NULL;
}

/**
 *  Page callback to view the translation of a pdf.
 *
 *  @param $object - FedoraObject - Tuque object containing the datastream
 *  @param $dsid - string - The id of the datastream in the Tuque object that contains
 *    the text
 */
function ucla_pdf_view_translation($object, $dsid) {
  $out = _ucla_pdf_format_datastream_text($object, $dsid);
  $out .= "<br/><a href='download_translation'>Download as txt</a>";
  return $out; 
}

/**
 *  Page callback to view the transcription of a pdf.
 *
 *  @param $object - FedoraObject - Tuque object containing the datastream
 *  @param $dsid - string - The id of the datastream in the Tuque object that contains
 *    the text
 */
function ucla_pdf_view_transcription($object, $dsid) {
  return _ucla_pdf_format_datastream_text($object, $dsid);
}
